[2023-03-28 10:27:12,265] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: defence_dag2.to_attack manual__2023-03-28T10:27:04.916029+00:00 [queued]>
[2023-03-28 10:27:12,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: defence_dag2.to_attack manual__2023-03-28T10:27:04.916029+00:00 [queued]>
[2023-03-28 10:27:12,278] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 10:27:12,279] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-28 10:27:12,280] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 10:27:12,296] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): to_attack> on 2023-03-28 10:27:04.916029+00:00
[2023-03-28 10:27:12,303] {standard_task_runner.py:52} INFO - Started process 1959 to run task
[2023-03-28 10:27:12,307] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'defence_dag2', 'to_attack', 'manual__2023-03-28T10:27:04.916029+00:00', '--job-id', '4221', '--raw', '--subdir', 'DAGS_FOLDER/defese.py', '--cfg-path', '/tmp/tmptzihnejd', '--error-file', '/tmp/tmp_ccdtbux']
[2023-03-28 10:27:12,308] {standard_task_runner.py:80} INFO - Job 4221: Subtask to_attack
[2023-03-28 10:27:12,362] {task_command.py:369} INFO - Running <TaskInstance: defence_dag2.to_attack manual__2023-03-28T10:27:04.916029+00:00 [running]> on host 70f8824ef075
[2023-03-28 10:27:12,427] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=defence_dag2
AIRFLOW_CTX_TASK_ID=to_attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T10:27:04.916029+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T10:27:04.916029+00:00
[2023-03-28 10:27:12,430] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-03-28 10:27:12,432] {client.py:777} INFO - Refreshing access_token
[2023-03-28 10:27:13,757] {config.py:55} INFO - set ART_DATA_PATH to /home/***/.art/data
[2023-03-28 10:27:14,070] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/art/estimators/certification/__init__.py:14: UserWarning: PyTorch not found. Not importing DeepZ or Interval Bound Propagation functionality
  warnings.warn("PyTorch not found. Not importing DeepZ or Interval Bound Propagation functionality")

[2023-03-28 10:27:14,184] {python.py:173} INFO - Done. Returned value was: trigger_offence
[2023-03-28 10:27:14,186] {skipmixin.py:140} INFO - Following branch trigger_offence
[2023-03-28 10:27:14,186] {skipmixin.py:175} INFO - Skipping tasks ['stop']
[2023-03-28 10:27:14,237] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=defence_dag2, task_id=to_attack, execution_date=20230328T102704, start_date=20230328T102712, end_date=20230328T102714
[2023-03-28 10:27:14,295] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-28 10:27:14,348] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
