[2023-03-27 12:02:29,964] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-27T12:02:27.945462+00:00 [queued]>
[2023-03-27 12:02:29,977] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-27T12:02:27.945462+00:00 [queued]>
[2023-03-27 12:02:29,978] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 12:02:29,978] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-27 12:02:29,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 12:02:29,995] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-27 12:02:27.945462+00:00
[2023-03-27 12:02:29,999] {standard_task_runner.py:52} INFO - Started process 151 to run task
[2023-03-27 12:02:30,002] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag2', 'attack', 'manual__2023-03-27T12:02:27.945462+00:00', '--job-id', '3884', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmpqqgcvr1u', '--error-file', '/tmp/tmppfoc94qx']
[2023-03-27 12:02:30,004] {standard_task_runner.py:80} INFO - Job 3884: Subtask attack
[2023-03-27 12:02:30,068] {task_command.py:369} INFO - Running <TaskInstance: attack_dag2.attack manual__2023-03-27T12:02:27.945462+00:00 [running]> on host 63267b5062fd
[2023-03-27 12:02:30,163] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag2
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T12:02:27.945462+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T12:02:27.945462+00:00
[2023-03-27 12:02:30,165] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack.py", line 18, in attack_A
    counter = load_from_bucket('counter.pickle')
  File "/opt/airflow/dags/helpers.py", line 30, in load_from_bucket
    bucket = get_client()
  File "/opt/airflow/dags/helpers.py", line 13, in get_client
    storage_client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/storage/client.py", line 53, in __init__
    http=http)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/client.py", line 185, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/client.py", line 141, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/client.py", line 154, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/_helpers.py", line 270, in _determine_default_project
    project = _file_project_id()
  File "/home/airflow/.local/lib/python3.7/site-packages/gcloud/_helpers.py", line 175, in _file_project_id
    with open(credentials_file_path, 'rb') as credentials_file:
FileNotFoundError: [Errno 2] No such file or directory: 'mabadata-733abc189d01.json'
[2023-03-27 12:02:30,185] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=attack_dag2, task_id=attack, execution_date=20230327T120227, start_date=20230327T120229, end_date=20230327T120230
[2023-03-27 12:02:30,198] {standard_task_runner.py:97} ERROR - Failed to execute job 3884 for task attack ([Errno 2] No such file or directory: 'mabadata-733abc189d01.json'; 151)
[2023-03-27 12:02:30,215] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-27 12:02:30,269] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
