[2023-04-30 11:08:46,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.trigger_defence manual__2023-04-30T11:02:44.097488+00:00 [queued]>
[2023-04-30 11:08:46,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.trigger_defence manual__2023-04-30T11:02:44.097488+00:00 [queued]>
[2023-04-30 11:08:46,203] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 11:08:46,209] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-30 11:08:46,210] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 11:08:46,238] {taskinstance.py:1377} INFO - Executing <Task(TriggerDagRunOperator): trigger_defence> on 2023-04-30 11:02:44.097488+00:00
[2023-04-30 11:08:46,250] {standard_task_runner.py:52} INFO - Started process 405 to run task
[2023-04-30 11:08:46,256] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'trigger_defence', 'manual__2023-04-30T11:02:44.097488+00:00', '--job-id', '7440', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmp2zkrufqk', '--error-file', '/tmp/tmp3oq9f4ed']
[2023-04-30 11:08:46,259] {standard_task_runner.py:80} INFO - Job 7440: Subtask trigger_defence
[2023-04-30 11:08:46,370] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.trigger_defence manual__2023-04-30T11:02:44.097488+00:00 [running]> on host 873e5d3a4399
[2023-04-30 11:08:46,504] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=trigger_defence
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T11:02:44.097488+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T11:02:44.097488+00:00
[2023-04-30 11:08:48,119] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=trigger_defence, execution_date=20230430T110244, start_date=20230430T110846, end_date=20230430T110848
[2023-04-30 11:08:48,158] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 11:08:48,193] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
