[2023-03-12 15:18:41,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag.attack manual__2023-03-12T15:18:39.614059+00:00 [queued]>
[2023-03-12 15:18:41,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag.attack manual__2023-03-12T15:18:39.614059+00:00 [queued]>
[2023-03-12 15:18:41,103] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-12 15:18:41,103] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-12 15:18:41,104] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-12 15:18:41,114] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-12 15:18:39.614059+00:00
[2023-03-12 15:18:41,118] {standard_task_runner.py:52} INFO - Started process 113 to run task
[2023-03-12 15:18:41,121] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag', 'attack', 'manual__2023-03-12T15:18:39.614059+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmpxxh39tof', '--error-file', '/tmp/tmpyaxgd23w']
[2023-03-12 15:18:41,121] {standard_task_runner.py:80} INFO - Job 442: Subtask attack
[2023-03-12 15:18:41,162] {task_command.py:369} INFO - Running <TaskInstance: attack_dag.attack manual__2023-03-12T15:18:39.614059+00:00 [running]> on host 596adcca7378
[2023-03-12 15:18:41,218] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-12T15:18:39.614059+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-12T15:18:39.614059+00:00
[2023-03-12 15:18:41,219] {logging_mixin.py:115} INFO - attacking!
[2023-03-12 15:18:41,220] {python.py:173} INFO - Done. Returned value was: None
[2023-03-12 15:18:41,233] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=attack_dag, task_id=attack, execution_date=20230312T151839, start_date=20230312T151841, end_date=20230312T151841
[2023-03-12 15:18:41,253] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-12 15:18:41,280] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
