[2023-03-23 15:31:54,044] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.trigger_defence manual__2023-03-23T15:20:41.365546+00:00 [queued]>
[2023-03-23 15:31:54,067] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.trigger_defence manual__2023-03-23T15:20:41.365546+00:00 [queued]>
[2023-03-23 15:31:54,068] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:31:54,069] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-03-23 15:31:54,069] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 15:31:54,094] {taskinstance.py:1377} INFO - Executing <Task(TriggerDagRunOperator): trigger_defence> on 2023-03-23 15:20:41.365546+00:00
[2023-03-23 15:31:54,103] {standard_task_runner.py:52} INFO - Started process 12289 to run task
[2023-03-23 15:31:54,112] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'trigger_defence', 'manual__2023-03-23T15:20:41.365546+00:00', '--job-id', '3087', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpg9ltblnx', '--error-file', '/tmp/tmpor8eub8g']
[2023-03-23 15:31:54,115] {standard_task_runner.py:80} INFO - Job 3087: Subtask trigger_defence
[2023-03-23 15:31:54,272] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.trigger_defence manual__2023-03-23T15:20:41.365546+00:00 [running]> on host 6447f1dacd32
[2023-03-23 15:31:55,780] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=trigger_defence
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T15:20:41.365546+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T15:20:41.365546+00:00
[2023-03-23 15:32:01,184] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=multi_attack_dag, task_id=trigger_defence, execution_date=20230323T152041, start_date=20230323T153154, end_date=20230323T153201
[2023-03-23 15:32:01,243] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-23 15:32:01,361] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
