[2023-03-28 10:00:34,990] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-28T10:00:33.021365+00:00 [queued]>
[2023-03-28 10:00:35,003] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-28T10:00:33.021365+00:00 [queued]>
[2023-03-28 10:00:35,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 10:00:35,004] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-28 10:00:35,005] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 10:00:35,019] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-28 10:00:33.021365+00:00
[2023-03-28 10:00:35,024] {standard_task_runner.py:52} INFO - Started process 1460 to run task
[2023-03-28 10:00:35,028] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag2', 'attack', 'manual__2023-03-28T10:00:33.021365+00:00', '--job-id', '4124', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmpl0rxzcvk', '--error-file', '/tmp/tmplhp2e8ao']
[2023-03-28 10:00:35,029] {standard_task_runner.py:80} INFO - Job 4124: Subtask attack
[2023-03-28 10:00:35,088] {task_command.py:369} INFO - Running <TaskInstance: attack_dag2.attack manual__2023-03-28T10:00:33.021365+00:00 [running]> on host 70f8824ef075
[2023-03-28 10:00:35,169] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag2
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T10:00:33.021365+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T10:00:33.021365+00:00
[2023-03-28 10:00:35,172] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-03-28 10:00:35,174] {client.py:777} INFO - Refreshing access_token
[2023-03-28 10:00:36,197] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-03-28 10:00:36,202] {client.py:777} INFO - Refreshing access_token
[2023-03-28 10:00:36,868] {python.py:173} INFO - Done. Returned value was: None
[2023-03-28 10:00:36,889] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=attack_dag2, task_id=attack, execution_date=20230328T100033, start_date=20230328T100034, end_date=20230328T100036
[2023-03-28 10:00:36,933] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-28 10:00:36,979] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
