[2023-03-19 12:06:52,216] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-19T12:06:51.268337+00:00 [queued]>
[2023-03-19 12:06:52,224] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: attack_dag2.attack manual__2023-03-19T12:06:51.268337+00:00 [queued]>
[2023-03-19 12:06:52,224] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-19 12:06:52,224] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-19 12:06:52,225] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-19 12:06:52,237] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack> on 2023-03-19 12:06:51.268337+00:00
[2023-03-19 12:06:52,241] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2023-03-19 12:06:52,243] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'attack_dag2', 'attack', 'manual__2023-03-19T12:06:51.268337+00:00', '--job-id', '1664', '--raw', '--subdir', 'DAGS_FOLDER/attack.py', '--cfg-path', '/tmp/tmp8nmuhrdj', '--error-file', '/tmp/tmpvwpq4s0h']
[2023-03-19 12:06:52,244] {standard_task_runner.py:80} INFO - Job 1664: Subtask attack
[2023-03-19 12:06:52,288] {task_command.py:369} INFO - Running <TaskInstance: attack_dag2.attack manual__2023-03-19T12:06:51.268337+00:00 [running]> on host de4be3e36311
[2023-03-19 12:06:52,348] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=attack_dag2
AIRFLOW_CTX_TASK_ID=attack
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T12:06:51.268337+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-19T12:06:51.268337+00:00
[2023-03-19 12:06:52,368] {logging_mixin.py:115} INFO - attacking!
[2023-03-19 12:06:52,368] {python.py:173} INFO - Done. Returned value was: None
[2023-03-19 12:06:52,378] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=attack_dag2, task_id=attack, execution_date=20230319T120651, start_date=20230319T120652, end_date=20230319T120652
[2023-03-19 12:06:52,417] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-19 12:06:52,444] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
